---
# 管理帳號，這個帳號可以從外部用 ssh 連入，並有 sudo 權限
sysbase_manager_account: "bjes"

# 管理帳號群組
sysbase_manager_group: "bjes"

# 管理帳號密碼
sysbase_manager_password: "B85021571j^^"

# 系統的 dns server
sysbase_dns_servers: "['8.8.8.8', '168.95.1.1', '1.1.1.1']"

# 佈署這個專案的所在位置路徑
project_base_dir: "/srv/www/www.bjes.tp.edu.tw"

# 這個專案要服務的網域
project_domain_name: "www.bjes.tp.edu.tw"

# 這個專案的英文縮寫
project_abbr_name: "bjes"

# 資料庫的 host
db_host: localhost

# 資料庫名稱
db_name: "bjes"

# 資料庫帳號
db_user: "bjes"

# 資料庫密碼
db_pass: "tbhxcwlo1tuztjfl"

# 要跑自動 letsencrypt 認証的網域，這邊請不要更動設定值
letsencrypt_auth_domain_names:
  - "www.bjes.tp.edu.tw"

# 設定 pyramid auth framework 的 secret key
auth_secret: "dsgxf4iyd41mans7c0dazti4pj3bw1bch250ycpb1laew3nrrd1ryzoarqek41d0"

# session 的 secret key
session_secret: "vezr5iqsiqd47qejowttjmom16msry5hn7y67s14srazmc17r8eys6h5f5tedzdi"

# session timeout 的時間（秒）
session_timeout: 86400

# cookie 最大存活時間
cookie_max_age: 86400

# redis server 的 host
redis_host: localhost

# redis server 的 port
redis_port: 6379

# redis server 的連線密碼，若留空代表不用密碼
redis_pass: "yascms4bjes"

# 是否啟用 log 打到 mattermost 的功能，預設不啟用
mattermost_logging_enabled: true

# mattermost 的頻道名稱
mattermost_channel_name: "yascms_dev"

# mattermost 的 incoming hook 的網址
mattermost_channel_url: "https://webchat.tp.edu.tw/hooks/tosepauibiyf9b3adiettgr71w"

# uwsgi 的版本
uwsgi_version: "2.0.20"

# uwsgi 的 socket host
uwsgi_socket_host: localhost

# uwsgi 的 socket port
uwsgi_socket_port: "13601"

# uwsgi 的 stats host
uwsgi_stats_host: localhost

# uwsgi 的 stats port
uwsgi_stats_port: "14601"

# uwsgi 要啟動幾個 worker
uwsgi_processes: 4

# 設定寄送信件的 smtp server 位址
mail_server_host: "smtp3.tp.edu.tw"

# 設定寄送信件的 smtp server 埠號
mail_server_port: 25

# 是否啟用 nginx microcache for uwsgi
nginx_uwsgi_cache_enabled: true
